spring.application.name=rekapin-be

spring.datasource.url=jdbc:mysql://localhost:3306/rekapin_db
spring.datasource.username=root
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

rekapin.jwt.secret=insert_secret_key_at_least_32_characters_here
rekapin.jwt.expiration=86400000